### ISSUE TITLE
Render TeX formula depending from slider?

### ISSUE THREAD

**Issue by axkr** [paulmasson/mathcell#1]
If I have an array of TeX formulas, is it possible to render these formulas in KaTeX or MathJAX?

For example, if I have ten formulas and an "integer" slider in the range 1..10 was moved a new formula from these ten formulas should be displayed.

See https://github.com/tranleduy2000/ncalc/issues/67

**Comment by paulmasson** [comment]
@axkr this is doable if you keep in mind that backslashes are used in JavaScript to escape characters. While there are different ways to handle this, the simplest appears to be to double them in all LaTeX and then replace them with a single HTML entity for rendering. Here is an example of the display you want:

https://paulmasson.github.io/mathcell/docs/examples/latex-display.html

**Comment by axkr** [comment]
Thanks for your suggestion. I now have a running prototype.
