### ISSUE TITLE
Colormaps in surface

### ISSUE THREAD

**Issue by nicoguaro** [paulmasson/mathcell#12]
Are there any other colormaps besides "jet"?

**Comment by paulmasson** [comment]
For any plot or surface, one can specify an option of `color` using standard HTML designations for color. For parametric surfaces one can specify an option of `colormap` which is a function returning a value between 0 and 1 for setting the color in an HSL color space. Here are a few examples using this option:

https://paulmasson.github.io/mathcell/docs/examples/cardinal-sine-3d.html
https://paulmasson.github.io/mathcell/docs/examples/sine-wave-3d.html
https://paulmasson.github.io/mathcell/docs/examples/hyperbolic-helicoid.html

**Comment by nicoguaro** [comment]
I understand it. But I would like to use other [colormaps](https://matplotlib.org/3.1.1/gallery/color/colormap_reference.html) different from the HSV/jet colormap.

**Comment by paulmasson** [comment]
You mean predefined colormaps. Those are not yet implemented. For future reference these links to matplotlib source code show how to define their colormaps:

[def colormaps()](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/pyplot.py#L1683)
[color data](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/_cm.py)
[LinearSegmentedColormaps](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/colors.py#L699)

**Comment by nicoguaro** [comment]
Thanks for the reply.

**Comment by paulmasson** [comment]
@nicoguaro I've implemented a `colormap()` command that returns a function taking input in the range [0,1] and outputs a color object with RGB values. Available predefined colormaps will be in a JavaScript [file](https://github.com/paulmasson/mathcell/blob/master/src/plot/colormaps.js) with that name. I still need to figure out how to automatically scale a colormap to vertex data, but you can start playing around with it if you like.

**Comment by paulmasson** [comment]
There now a dozen predefined colormaps that can be seen [here](https://paulmasson.github.io/mathcell/docs/colormaps.html) and that can be applied to surfaces. This [example](https://paulmasson.github.io/mathcell/docs/examples/cardinal-sine-3d.html) has been updated to use the new colormaps functionality available in Version 1.8.0 of the library.

Thanks for suggesting this and let me know if you encounter any difficulties or errors in using it!

**Comment by nicoguaro** [comment]
It works nicely, thanks!

![image](https://user-images.githubusercontent.com/1097787/68346993-a54b0000-00c3-11ea-8dd4-e24d6ced68ae.png)
