### ISSUE TITLE
Loading iframes faster

### ISSUE THREAD

**Issue by paulmasson** [paulmasson/mathcell#14]
@theo-armour any thoughts on this? Perhaps loading via `contentWindow` is faster than `srcdoc`

**Comment by theo-armour** [comment]
@paulmasson 

Some quick, untested observations:

https://github.com/paulmasson/mathcell/blob/master/build/mathcell.js#L2078

>  // apply aspect multipliers for convenience
>  s.vertices.forEach( v => { v[0] *= a[0]; v[1] *= a[1]; v[2] *= a[2]; } );

Have you looked at mesh.scale,set()? might be faster the multiplying each vertex


https://github.com/paulmasson/mathcell/blob/master/build/mathcell.js#L2081-L2096

>  // remove faces completely outside vertical range
> // remove faces completely outside vertical range

Are these tweaks really helpful?

Three.js by itself culls back faces

see: https://threejs.org/docs/#api/en/constants/Renderer

And I am fairly certain that anything outside the camera frustum is also ignored automatically.

See: https://threejs.org/docs/#api/en/cameras/PerspectiveCamera

```
  for ( var i = 0 ; i < s.vertices.length ; i++ ) {
    var v = s.vertices[i];
    geometry.vertices.push( new THREE.Vector3( v[0], v[1], v[2] ) );
  }
```
or  
```
const vertices = s.vertices.map( vertex => new THREE.Vector3().fromArray( vertex )  );
```

**Comment by paulmasson** [comment]
> https://github.com/paulmasson/mathcell/blob/master/build/mathcell.js#L2078
> 
> > // apply aspect multipliers for convenience
> > s.vertices.forEach( v => { v[0] *= a[0]; v[1] *= a[1]; v[2] *= a[2]; } );
> 
> Have you looked at mesh.scale,set()? might be faster the multiplying each vertex

This is an interesting idea from the point of view of cleaner code, but since Three.js has to do a similar multiplication at some point I'd rather keep these aspect multipliers explicit and under my control. They are used to set the positions of multiple types of objects throughout the template. I don't think I'll save too much by eliminating a one-time application.

> 
> https://github.com/paulmasson/mathcell/blob/master/build/mathcell.js#L2081-L2096
> 
> > // remove faces completely outside vertical range
> > // remove faces completely outside vertical range
> 
> Are these tweaks really helpful?
> 
> Three.js by itself culls back faces
> 
> see: https://threejs.org/docs/#api/en/constants/Renderer
> 
> And I am fairly certain that anything outside the camera frustum is also ignored automatically.
> 
> See: https://threejs.org/docs/#api/en/cameras/PerspectiveCamera
> 

Removing faces outside of the vertical range of the graphic is not connected to culling of faces: it's used to prune functions that blow up in either vertical direction. The graphics look terrible if this is not done.

> ```
>   for ( var i = 0 ; i < s.vertices.length ; i++ ) {
>     var v = s.vertices[i];
>     geometry.vertices.push( new THREE.Vector3( v[0], v[1], v[2] ) );
>   }
> ```
> 
> or
> 
> ```
> const vertices = s.vertices.map( vertex => new THREE.Vector3().fromArray( vertex )  );
> ```

Is this function any faster that just doing it one at a time explicitly? Sounds like the same amount of work just stated differently. Besides, `map` makes a copy of the original array.

**Comment by paulmasson** [comment]
@theo-armour I don't think the bottleneck is the template, but rather just getting info into the iframe. Thought you might have some ideas about that based on how you've been working.

**Comment by paulmasson** [comment]
Waiting for `contentWindow` is slower than `srcdoc`:
https://stackoverflow.com/questions/56195634/create-new-iframe-and-load-content-synchronously
