### ISSUE TITLE
consider x3d as xml and in inline

### ISSUE THREAD

**Issue by andreasplesch** [paulmasson/mathcell#15]
One of the benefits of x3d is that multiple render engines or x3d browsers exist, for the web but also outside of the web, even for 3d printing. For compatibility it is important to stay close to the official XML encoding. To turn the x3dom html you already have into XML only a few minor tweaks are required. x3dom will still be able to render the x3d if it is loaded as an Inline. In addition, it will be straightforward to offer an x_ite render output option, or a x3d xml download for offline viewing with freewrl or view3dscene, and perhaps for 3d printing.
Possibly something to consider. I would certainly be available to help.

**Comment by paulmasson** [comment]
@andreasplesch the intent of this library is to embed interactive graphics in web pages. If I understand you correctly, you are recommending that I produce an XML file first that can then be embedded in HTML or consumed elsewhere. It's an interesting idea, but who would be the target audience for a work flow that creates XML using a graphic embedded in a web page?

**Comment by andreasplesch** [comment]
You are right, the first question would be if there is interest  in widening the intent of the library.

A more immediate benefit would be the ability to evaluate x_ite in comparison to x3dom.

A potential audience would be practitioners who see value in the durability and archival quality of plots which are described by a well defined format. A published document using HTML and X3D would have a chance to be rendered as intended in 20 years.

I just thought there would be significant added value for a relatively small investment.

**Comment by paulmasson** [comment]
It occurred to me that it would be very simple to add a download button that grabs the XML element and saves it to a file, so it would really not be much work. Are there specific issues with the XML as already written?

**Comment by andreasplesch** [comment]
Here is an example of a proper xml x3d file:

https://x3dgraphics.com/examples/X3dForAdvancedModeling/AdditiveManufacturing/CaffeinePubChem2519SticksColorIndex.html

The main items are the first two lines: the xml declaration and the doctype
https://www.web3d.org/documents/specifications/19776-1/V3.3/Part01/concepts.html#Header

It is good style to add some meta information, either in the header, or in a Metadata node, for example in a WorldInfo node, for the case when the x3d content becomes separated from its context.

XML is case sensitive, in contrast to HTML. But I think you have the proper cases for all nodes and fields.

Finally, I think I saw a use of `<Coordinate .. />`, eg. a self closing tag. This is ok for XML but usually does not work for HTML parsers. It is safer to use `<Coordinate></Coordinate>`.

You could use an ObjectURL and a DataURL to represent the file, both for downloading and for the url field of an Inline node.

**Comment by paulmasson** [comment]
Took a bit more work that anticipated but can now download XML and choose between two viewers. You can showcase it with this example:

https://paulmasson.github.io/mathcell/docs/examples/x3d-test.html

There is  difference in default orientation between the two viewers. Also x_ite doesn't appear to render everything and is so slooooowwwwww..

**Comment by andreasplesch** [comment]
I may have a look. First at the Viewpoint.

**Comment by andreasplesch** [comment]
view3dscene renders the view orientation as x3dom:
![image](https://user-images.githubusercontent.com/6171115/72747293-33db0380-3b82-11ea-9e80-a8b1cbb14e46.png)

So it is probably an issue with x_ite. It may be due to the align horizontal option since horizontal is the X-Z plane in X3D (and three) by default.

I think the white spheres are an issue with TwoSidedMaterial and view3dscene.

The missing black lines for the box in x_ite are due to a missing material. x3dom is more forgiving.

I will supply a PR for black lines, shortly.

**Comment by andreasplesch** [comment]
The view issue was due the Straighten Horizon option of x_ite which is on by default. I added a few line s to #17 to disable that option.

**Comment by paulmasson** [comment]
Most of this issue has been covered, apart from the suggestion about loading as Inline. Could you expand on that idea? Also, how do ObjectURL and DataURL fit into this?

**Comment by andreasplesch** [comment]
The idea was to use an Inline with x3dom since the Inline accepts standard x3d xml. x_ite could use the x3d xml with the X3DCanvas src attribute. So the html would be very simple:

For x3dom
```xml
<X3D>
  <Scene>
    <Inline url='x3dxml_url'></Inline>
  </Scene>
</X3D>
```
For x_ite
```xml
<X3DCanvas src='x3dxml_url'></X3DCanvas>
```
and you would not need my x_ite dom bridge.

Since you cannot really use files with html, you can create Object or DataURLs for the x3d xml url, as you are already doing for the download.

But when I tried this a little bit, I ran into problems, perhaps having to do with the iframe and with the missing extension in the url which is used to decide how the x3d is encoded.

So it may not be worth the trouble.

**Comment by andreasplesch** [comment]
The latest view3dscene has TwoSidedMaterial fixed: 
![image](https://user-images.githubusercontent.com/6171115/72765432-64d72a80-3bba-11ea-836e-48619f111eb2.png)

**Comment by paulmasson** [comment]
Since I prefer generating everything in the browser, as opposed to the load-from-file mindset, I'll leave things as they are for now. Thanks again for recommending the changes: they're nice features to have.
