### ISSUE TITLE
Support Mathematica colormaps

### ISSUE THREAD

**Issue by paulmasson** [paulmasson/mathcell#18]
Data for Mathemtica [colormaps](https://reference.wolfram.com/language/guide/ColorSchemes.html) can be extracted numerically using

    InputForm /@ ColorData["CherryTones"] /@ Range[0, 1, .1]

Initially supported schemes should include SunsetColors, WatermelonColors, Rainbow, TemperatureMap, LightTemperatureMap, DarkRainbow, RustTones and the default M10DefaultDensityGradient.

This approach has been used in at least one open source [project](https://github.com/idsc-frazzoli/tensor#visualization). Color data of this sort is available [here](https://github.com/idsc-frazzoli/tensor/tree/master/src/main/resources/colorscheme).

If would be preferable to have a mathematical statement of the colormap as is true for most of the [maps](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/_cm.py) in matplotlib. @axkr are you aware of any open source project that replicates the Mathematica colormaps with expressions of this sort, or do they all sample the data numerically?

**Comment by axkr** [comment]
@paulmasson No I'm not aware of any project.

**Comment by axkr** [comment]
Similar project like mathcell, but can't find colormaps:
- https://github.com/JerryI/Mathematica-ThreeJS-graphics-engine

**Comment by paulmasson** [comment]
@axkr added seven Mathematica colormaps in 1126d96. That covers most of what you wanted and can be extended later. First want to write up the method.

**Comment by paulmasson** [comment]
New version for colormaps: https://github.com/paulmasson/mathcell/releases/tag/1.8.8

Method described here: [Reverse Engineering Mathematica Colormaps](https://analyticphysics.com/Coding%20Methods/Reverse%20Engineering%20Mathematica%20Colormaps.htm)
