### ISSUE TITLE
Contour and density plot any examples?

### ISSUE THREAD

**Issue by axkr** [paulmasson/mathcell#20]
Do you have any examples for a contour or density plot?

How to use `isoband` for a contour plot?
- https://paulmasson.github.io/mathcell/docs/index.html

My attempt looks like this:
```
<html>
<head>
<meta charset="utf-8">
<title>MathCell</title>
<link rel="stylesheet" type="text/css" href="style.css">
</head>

<body>
<script src="https://cdn.jsdelivr.net/gh/paulmasson/math@1.2.9/build/math.js"></script>

<script src="https://cdn.jsdelivr.net/gh/paulmasson/mathcell@1.8.8/build/mathcell.js"></script>
<div class="mathcell" style="width: 100%; height: 100%; padding: .25in .5in .5in .5in;">
<script>

var parent = document.scripts[ document.scripts.length - 1 ].parentNode;

var id = generateId();
parent.id = id;

MathCell( id, [  ] );

parent.update = function( id ) {


function z1(x,y) { return [ x, y, add(cos(x),cos(y)) ]; }

var p1 = isoband( z1, [0, (12.566370614359172)], [0, (12.566370614359172)] );

  var config = { type: 'threejs' };
  var data = [p1];
evaluate( id, data, config );

}

parent.update( id );

</script>
</div>

</body>
</html>
```

**Comment by paulmasson** [comment]
@axkr sorry for the late reply. An isoband plot shows a region in 2D where the input function is less than a set level, by default zero. With this default level, the region between two functions can be found by multiplying them.

Here's a fun example of animated square isobands:

https://paulmasson.github.io/mathcell/docs/examples/square-isobands.html

I don't support density plots yet. Will have to think about that.

You might also want to use this line in your template, as it's perhaps a bit safer for runtime:

`var parent = document.currentScript.parentNode;`
