### ISSUE TITLE
Automatically catch errors in plotting

### ISSUE THREAD

**Issue by paulmasson** [paulmasson/mathcell#21]
Question from @axkr on Gitter:

> @paulmasson is it correct to wrap the generated JavaScript funtion with a try { } catch(err) { return Number.Nan; }, so that the plotter can go on with rendering, or is there another preferrred mechanism?

@axkr please provide an example that goes wrong. Besides `NaN`, an error would result from `Infinity` and possibly other values. Thanks!

**Comment by paulmasson** [comment]
This example does not involve `NaN` issues: you're hitting the poles of the gamma function at negative integers. Changing the limits slightly moves you off the poles, as would using an odd number of evaluation points, which is the workaround I've been using.

I currently throw errors for both the gamma and hypergeometric poles, which of course stops evaluation dead. I don't see any better way to handle those situations, since you really can't evaluate the functions at poles. Even if I returned `Infinity`, it would still need a sign to be useful, which would require a direction of approach to the pole.

Need to think about this more...

**Comment by axkr** [comment]
Is #22 a possible solution?

**Comment by paulmasson** [comment]
> Is #22 a possible solution?
Throwing gamma function pole errors prevents plot generation, so no this will help with that issue

**Comment by paulmasson** [comment]
See https://github.com/paulmasson/mathcell/issues/22#issuecomment-774465540
