### ISSUE TITLE
JSON.stringify() filter out "null" values

### ISSUE THREAD

**Issue by axkr** [paulmasson/mathcell#22]
As this function should only plot the available data here:
https://github.com/paulmasson/mathcell/blob/f3ecf34572f53a89c822e9eee413d0db328b13dd/src/render/svg.js#L4

Doesn't it make sense to "filter out" the "undefined" values with a second replacer argument to stringify()?
- [Using a Replacer Function with JSON.stringify](https://www.dyn-web.com/tutorials/php-js/json/filter.php)

Or splitting the original `data` in multiple "data" parts which recursively call `svg()` for each part?

**Comment by axkr** [comment]
Can the problem with `Cot` in the following example solved with this approach?

```
<html>
<head>
<meta charset="utf-8">
<title>MathCell</title>
<link rel="stylesheet" type="text/css" href="style.css">
</head>

<body>
<script src="https://cdn.jsdelivr.net/gh/paulmasson/math@1.4.0/build/math.js"></script>

<script src="https://cdn.jsdelivr.net/gh/paulmasson/mathcell@1.8.8/build/mathcell.js"></script>
<script src="https://cdn.jsdelivr.net/gh/mathjax/MathJax@2.7.5/MathJax.js?config=TeX-AMS_HTML"></script>
<div class="mathcell" style="width: 100%; height: 100%; padding: .25in .5in .5in .5in;">
<script>

var parent = document.currentScript.parentNode;

var id = generateId();
parent.id = id;

MathCell( id, [ { type: 'buttons', values: ['sin','cos','tan','cot'], labels: ['Sin','Cos','Tan','Cot'], name: 'f', label: 'f' }
 ] );

parent.update = function( id ) {

var f = getVariable(id, 'f');

function z1(x) { return (window[f]((x))); }

var p1 = plot( z1, [0, (6.283185307179586)], { color: 'hsl(0,100%,50%)' } );
var data = [ p1 ];
var config = { type: 'svg'  };
evaluate( id, data, config );

}

parent.update( id );

</script>
</div>

</body>
</html>
```

**Comment by paulmasson** [comment]
@axkr the `data` object passed to the rendering functions can contain multiple type of objects, so splitting it up at run time is not feasible. I personally like having the plot fail, so that I know explicitly that there is an error in the data.

That being said, replacing `null` with something else is a good idea to keep things working for other users. It can be either zero or some large positive or negative number. Using zero of course leads to artifacts in the plots. I tend towards using the largest possible positive number, because the library already filters out huge values when limits are set vertically.

Using the last and adding vertical limits to your example allows it to work just fine. What do you think?

**Comment by paulmasson** [comment]
@axkr after some thinking it might be better to catch infinite values when creating the plot and setting them to appropriate large numbers, but that's additional overhead mostly not needed. Will ponder overnight.

**Comment by axkr** [comment]
> Using the last and adding vertical limits to your example allows it to work just fine. What do you think?

I think at least improve the current plots and be suitable as a work around.

**Comment by axkr** [comment]
> Using the last and adding vertical limits to your example allows it to work just fine. What do you think?

It will at least be a workaround, which shows some data.

**Comment by paulmasson** [comment]
@axkr with a13f7ef the plot function now checks numerical values for infinities and NaN, thus allowing something to appear. For now this will only apply to 2D plots, because I don't want to add overhead to the production of 3D graphics.

**Comment by paulmasson** [comment]
Fixed in [1.9.0](https://github.com/paulmasson/mathcell/releases/tag/1.9.0)

**Comment by paulmasson** [comment]
@axk as of 7f432d1 I've rewritten the SVG renderer to automatically skip over NaN values in the dependent variable. That should help with plot production in general. Let me know if you run across any problems with this feature.

**Comment by axkr** [comment]
Can you add a more detailed documentation how to handle "singularity", "function pole" and other exceptions? 
Not only for the "real number" case but also for "complex numbers" (see #21).

Should a function always be wrapped by a `try {   } catch(e) {  return XXX; }` block?
What should be returned (XXX) in the exceptions cases, so the plot can be "continued" by mathcell?

If I return `NaN` or `complex(NaN,NaN)` in the plot from #21 it doesn't work.

**Comment by paulmasson** [comment]
The functions currently throwing pole errors in Math are gamma, all hypergeometrics, lambertW, and both Riemann and Hurwitz zeta. Until I figure out a better way to return values, those functions at least need the try/catch block.

The  functionality recently added to MathCell is meant to automatically skip over complex values so that something appears even though the input function is expected to be purely real. Returning a complex zero is not wrong and probably what you should do at this point.

Returing `NaN` won't work right now because it is converted to `null` when making a local copy of the line. I need to think about doing better on this. Returning `complex(NaN)` will work because it is converted to `complex(null)`.

**Comment by axkr** [comment]
Returning `complex(NaN)`won't work. It throws error in this line:
- https://github.com/paulmasson/mathcell/blob/7f432d1713b1f2333b9bced502305f7fd4b552b6/build/mathcell.js#L3075

Example:

```
<html>
<head>
<meta charset="utf-8">
<title>MathCell</title>
<link rel="stylesheet" type="text/css" href="style.css">
</head>

<body>
<script src="https://cdn.jsdelivr.net/gh/paulmasson/math@1.4.4/build/math.js"></script>

<script src="mathcell.js"></script>
<div class="mathcell" style="width: 100%; height: 100%; padding: .25in .5in .5in .5in;">
<script>

var parent = document.currentScript.parentNode;

var id = generateId();
parent.id = id;

MathCell( id, [  ] );

parent.update = function( id ) {


function z1(z) { try {return mul(pow(z,-2),add(-1,pow(z,4)));}catch(e){return complex(NaN);}  }

var p1 = parametric( (re,im) => [ re, im, z1(complex(re,im)) ], [-2.0, 2.0], [-2.0, 2.0], { complexFunction: 'abs', colormap: 'complexArgument' } );

  var config = { type: 'threejs', zMin: 0, zMax: 8 };
  var data = [p1];
evaluate( id, data, config );

}

parent.update( id );

</script>
</div>

</body>
</html>
```

**Comment by paulmasson** [comment]
Right you are about the Three.js! Sorry, was thinking only about SVG and haven't addressed errors in 3D plots yet. So you are also right that returning complex zero distorts the 3D plot.

Skipping points is easy in 2D. Smoothing over holes in 3D will take some more thinking...

**Comment by axkr** [comment]
I think it will be good to have a "best practice" documentation page for the main possible cases in 2D and 3D and related examples to illustrate the "best practice" and how a plot "solution" looks in these cases.

**Comment by paulmasson** [comment]
Now that I finally understand JSON replacer/reviver functions, as of a664665 your example above should work. The lines to check for errors have been replaced with consistent copies that replace infinities with large numbers but leave `NaN` in place. The current `threejs()` function replaces the latter with `null` which computes to zero, so be aware of that for now.

**Comment by paulmasson** [comment]
@axkr sorry use a27100c. Forgot to update the build...

**Comment by axkr** [comment]
The plots are continued now.

For exceptions I'm returning now `complex(Number.NaN)`

**Comment by paulmasson** [comment]
@axkr as of 35e78be the Three.js template filters out NaN points on lines and any surface faces with a NaN vertex. Let me know if you encounter any problems from this new functionality.

**Comment by axkr** [comment]
For my examples it works. So issue #21 also seems to be solved.
