### ISSUE TITLE
Let MathCell calculate the aspect ratio

### ISSUE THREAD

**Issue by axkr** [paulmasson/mathcell#27]
Is there an option to let MathCell automatically calculate the aspect ratio

See: https://reference.wolfram.com/language/ref/AspectRatio.html

Example: 
- https://jsfiddle.net/axelclk/jrqfed2z/1/

**Comment by paulmasson** [comment]
@axkr 2D SVG plots automatically fill the entire available space. The appearance of the image in this space can be adjusted with `equalLimits` or `equalAspect`. The first just makes `x` and `y` have the same larger extent of the two.

For 3D plots, if you omit `aspectRatio` then the data in the `z`-direction is scaled to the radial average of the other two axes to give approximately a cubic space:

https://github.com/paulmasson/mathcell/blob/0771f56067cc255c136f5c124fdf456131bf7e40/src/render/threejs-template.js#L52

Is there something more you intended with the issue?

**Comment by axkr** [comment]
If I delete the `aspectRatio: [1.0,1,1.0/220.0]` in the jsFiddle example, it doesn't look like a "cubic  space". Can you modify the jsFiddle example to show what you mean?

**Comment by paulmasson** [comment]
@axkr the frame is roughly a cube. Actually taller in z-direction by sqrt(2):

https://jsfiddle.net/7hdw4sr9/

**Comment by paulmasson** [comment]
@axkr reopen this issue if you need anything else here.
