### ISSUE TITLE
ComplexPlot3D(Arg(z),  {z, -2 - 2*I, 2 + 2*I} ) doesn't display a graph

### ISSUE THREAD

**Issue by axkr** [paulmasson/mathcell#28]
`ComplexPlot3D(Arg(z),  {z, -2 - 2*I, 2 + 2*I} )` doesn't display a graph

This is the corresponding HTML page:

```xml
<html>
<head>
<meta charset="utf-8">
<title>MathCell</title>
</head>

<body>
<script src="https://cdn.jsdelivr.net/gh/paulmasson/math@1.4.9/build/math.js"></script>
<script src="https://cdn.jsdelivr.net/gh/paulmasson/mathcell@1.9.3/build/mathcell.js"></script>

<div class="mathcell" style="width: 100%; height: 100%; padding: .25in .5in .5in .5in;">
<script>
var parent = document.currentScript.parentNode;
var id = generateId();
parent.id = id;
MathCell( id, [  ] );

parent.update = function( id ) {


function z1(z) { try { return  arg(z);}catch(e){return complex(Number.NaN);} }

var p1 = parametric( (re,im) => [ re, im, z1(complex(re,im)) ], [-2.0, 2.0], [-2.0, 2.0], { complexFunction: 'abs', colormap: 'complexArgument' } );

  var config = { type: 'threejs', aspectRatio: [1.0,1,1] };
  var data = [p1];
evaluate( id, data, config );

}
parent.update( id );

</script>
 
</div>
</body>
</html>
```

**Comment by paulmasson** [comment]
@axkr the argument of a complex number is a real number. The option `complexFunction` on `parametric` expects the return value to be a complex number. I could add a check for real functions in the code if that would be helpful in the future.

**Comment by axkr** [comment]
@paulmasson this change works, but it will of course be easier, if mathcell will do the conversion to a complex number automatically:

```js
function z1(z) { try { return complex(0,arg(z));}catch(e){return complex(Number.NaN);} }
```

**Comment by paulmasson** [comment]
@axkr I agree that it is better to show output rather than silently fail. Should be fixed in [5bd5ed1](https://github.com/paulmasson/mathcell/commit/5bd5ed151329c5bf28ebd114d743b9556e6a4dd2). Please give it a try.

**Comment by axkr** [comment]
LGTM

**Comment by paulmasson** [comment]
Thanks!

**Comment by paulmasson** [comment]
@axkr commit [5fe54da](https://github.com/paulmasson/mathcell/commit/5fe54dadaacdd7b564860139d3dcdbdd8f40cf96) now allows non-vector functions to render in `parametric` and `wireframe`. For now treating this as a minor error with a console message, but perhaps should view it as a feature...
