### ISSUE TITLE
"Translation" animation with step=0

### ISSUE THREAD

**Issue by kperry42** [paulmasson/mathcell#30]
I like the new the "translation" animation feature, it's very nice.  One detail, though - it doesn't allow for setting a translation with "step" = 0.  This would be helpful if one wants to build several items with computed properties.  For instance in this simple example of an expanding row of boxes, where the middle one should stay at the origin:

    data = [];
    for (let j = -2, j <= 2; j++) {
        data.push(box(1, 1, 1, {translation: {path:'[t, 0, 0]', step: j/10}}));
    }

... you don't want to have to write special-case code to remove the translation with step=0.

Currently, threejs-template.js line 421 has:

    var step = s.options.translation.step ? s.options.translation.step : .05;

This causes "s.options.translation.step = 0" to map to "step = .05".  Using Number.isFinite() here instead would be an improvement:

    var step = Number.isFinite(s.options.translation.step) ? s.options.translation.step : .05;

This will map undefined, null, false, and invalid values to the default, but allow 0 as a possible value.

**Comment by paulmasson** [comment]
@kperry42 I don't have a problem with this change. Would you like to submit a pull request to get credit for the enhancement?

**Comment by paulmasson** [comment]
@kperry42 just a heads-up that I'm modifying the format of the translation `path` value slightly in the next version of the library. The vector function can still be entered as a string, but the argument must be included at the start of the string. In the example above you would just need to add "t=>" before the vector.

This change allows the `path` to be given as a function or its string representation. The `arg` parameter will be removed as redundant.
