### ISSUE TITLE
Setting material properties

### ISSUE THREAD

**Issue by kperry42** [paulmasson/mathcell#31]
It would be a quick, easy win to allow the passing of options for the material properties you're currently hard-coding in threejs-template (lines 373, 382) - "metalness" and "roughness" for Standard material type and "shininess" for Phong material type.  E.g. for metalness, just use:

     metalness: s.options.metalness >= 0 ? s.options.metalness : .5,

**Comment by paulmasson** [comment]
@kperry42 do you have a complete list of properties in mind or just these three?

**Comment by kperry42** [comment]
Those three cover the basics, and are good enough for me.  Anything more would require figuring out how to support things like bump map textures, etc., which sounds like maybe more trouble than it's worth.
