### ISSUE TITLE
"best practice" to show errors from evaluating a function

### ISSUE THREAD

**Issue by axkr** [paulmasson/mathcell#7]
If `math.js` throws an exception in evaluating a function, whats the preferred "best practice" to show the error in `mathcell.js` ?

**Comment by paulmasson** [comment]
The errors thrown in Math show up in the JavaScript console as uncaught exceptions. Is this sufficient for your purposes or did you have something else in mind?

**Comment by axkr** [comment]
Sometimes I get an "empty HTML frame" in the web interface http://matheclipse.org/ from a command like below, because the function name ("TestFunction" in this case) is undefined, or the Math.js lib  throws an exception like  'Unsupported elliptic nome'. 

For all these cases it would be nice to have a least a "status" output line with the error message.

```
 Plot(TestFunction(x), {x, -2*Pi, 2*Pi},PlotRange->{-1,1})
```

**Comment by paulmasson** [comment]
I've devised a way to automatically show errors in the MathCell, but it is browser dependent. For errors in the code of the cell, like undefined functions, it should work fine for all browsers because the error is local. For numerical errors coming from Math it displays a useful message in Firefox, but Chrome denies access to the full `Error` object and only displays a generic `'Script error.'` for security reasons.

If you want to try it out, you'll need to use version 1.2.4 of Math and 1.7.5 of MathCell.

**Comment by axkr** [comment]
Thanks, this is much better than showing an empty frame (in my "dynamic" use case) and let the user search in the browser console.

**Comment by axkr** [comment]
In `mathcell.js:311:23` I get this (translated) message only in the Firefox console:

> "Unexpected value NaN parsing attribute y"

```
<html>
<head>
<meta charset="utf-8">
<title>MathCell</title>
</head>

<body>

<script src="https://cdn.jsdelivr.net/gh/paulmasson/math@1.2.4/build/math.js"></script>
<script src="https://cdn.jsdelivr.net/gh/paulmasson/mathcell@1.7.5/build/mathcell.js"></script>
<script src="https://cdn.jsdelivr.net/gh/mathjax/MathJax@2.7.5/MathJax.js?config=TeX-AMS_HTML"></script>
<p style="text-align: center; line-height: 2"><span style="font-size: 20pt">MathCell</span></p>

<div class="mathcell" style="height: 4in">
<script>

var parent = document.scripts[ document.scripts.length - 1 ].parentNode;

var id = generateId();
parent.id = id;

MathCell( id, [ { type: 'buttons', values: ['cot','tan','sin','cos'], labels: ['Cot','Tan','Sin','Cos'], name: 'f', label: 'f' }
 ] );

parent.update = function( id ) {

var f = getVariable(id, 'f');

function z1(x) { return (window[f]((x))); }

var p1 = plot( z1, [0, (6.283185307179586)], { } );
var data = [ p1 ];
var config = { type: 'svg'  };
evaluate( id, data, config );

}

parent.update( id );

</script>
</div>

</body>
</html>
```

**Comment by paulmasson** [comment]
I've added a check to plotting outputs to catch bad input.

Try version 1.7.6 and see if it takes care of this issue.

**Comment by axkr** [comment]
Now it displays an error "Error: Infinity or `NaN` in input data" for example above.

But why isn't the `cot(x)` function not displayed?

**Comment by paulmasson** [comment]
Because `cot(0)=Infinity` and subsequent rounding operations lead to an indeterminant `NaN` that messes up the plotting. Need to avoid the exact origin.

**Comment by paulmasson** [comment]
I've discovered the trick I'm using to get a reference to the bad cell only works on the first load of the page. That may be enough for you, but I'll keep thinking about how to improve on this version.

**Comment by paulmasson** [comment]
Figured out how to track active cells easily. Now if the cell initially has no error but develops one after manipulation of interacts, the error message should be displayed. Version 1.7.7 has the fix.

**Comment by axkr** [comment]
The `cot(x)` function plot isn't displayed in the example above, if I replace with version 1.7.7.

Only the error message `Error: Infinity or NaN in input data` is displayed

**Comment by paulmasson** [comment]
> The `cot(x)` function plot isn't displayed in the example above, if I replace with version 1.7.7.
> 
> Only the error message `Error: Infinity or NaN in input data` is displayed

Because there is a singularity at the origin
