### ISSUE TITLE
Link to MathCell demo

### ISSUE THREAD

**Issue by theo-armour** [paulmasson/mathcell#9]
I am looking at the top of the MathCell GitHub repo

![image](https://user-images.githubusercontent.com/547626/65482061-a6460c00-de4c-11e9-8d8d-a8b06123d8d6.png)

It would be nice to have a link here to to a working demo of MathCell - which you can set when editing the description.

Alse the description could be more descriptive - for example: ""Interactive 2D and 3D mathematics visualizations in your browser""

**Comment by paulmasson** [comment]
Since I own the domain, I've added the link. I like the concise description up top, but I've expanded it down below and added links for #10.
